import { CaseDetailDTO, T2CaseDetailDTO, SACaseDetailDTO, FilingPeriod } from './models';

export const dummyT2CaseDetailDTOs: T2CaseDetailDTO[] = [
  { caseNumber: 'T2-001', clientName: 'John Doe', accountNumber: 'ACC-12345', caseStatus: 'Active', assignedUserId: 'USER-001', assignedUerName: 'Jane Smith', officeNameEn: 'Toronto Office', officeNameFn: 'Bureau de Toronto', caseType: 'T2 Corporate', category: 'Tax Return', createdDate: new Date(2024, 0, 15), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-001' },
  { caseNumber: 'T2-002', clientName: 'Alice Johnson', accountNumber: 'ACC-12346', caseStatus: 'Pending', assignedUserId: 'USER-002', assignedUerName: 'Bob Wilson', officeNameEn: 'Vancouver Office', officeNameFn: 'Bureau de Vancouver', caseType: 'T2 Partnership', category: 'Amendment', createdDate: new Date(2024, 1, 20), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-002' },
  { caseNumber: 'T2-003', clientName: 'Mike Brown', accountNumber: 'ACC-12347', caseStatus: 'Closed', assignedUserId: 'USER-003', assignedUerName: 'Carol Davis', officeNameEn: 'Montreal Office', officeNameFn: 'Bureau de Montréal', caseType: 'T2 Trust', category: 'Objection', createdDate: new Date(2024, 2, 10), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-003' },
  { caseNumber: 'T2-004', clientName: 'Sarah Wilson', accountNumber: 'ACC-12348', caseStatus: 'Active', assignedUserId: 'USER-004', assignedUerName: 'David Lee', officeNameEn: 'Calgary Office', officeNameFn: 'Bureau de Calgary', caseType: 'T2 Corporate', category: 'Tax Return', createdDate: new Date(2024, 3, 5), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-004' },
  { caseNumber: 'T2-005', clientName: 'Tom Anderson', accountNumber: 'ACC-12349', caseStatus: 'Review', assignedUserId: 'USER-005', assignedUerName: 'Emma Taylor', officeNameEn: 'Ottawa Office', officeNameFn: 'Bureau d\'Ottawa', caseType: 'T2 Partnership', category: 'Amendment', createdDate: new Date(2024, 4, 12), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-005' },
  { caseNumber: 'T2-006', clientName: 'Lisa Garcia', accountNumber: 'ACC-12350', caseStatus: 'Active', assignedUserId: 'USER-006', assignedUerName: 'Frank Miller', officeNameEn: 'Halifax Office', officeNameFn: 'Bureau d\'Halifax', caseType: 'T2 Trust', category: 'Objection', createdDate: new Date(2024, 5, 8), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-006' },
  { caseNumber: 'T2-007', clientName: 'James Martinez', accountNumber: 'ACC-12351', caseStatus: 'Pending', assignedUserId: 'USER-007', assignedUerName: 'Grace Chen', officeNameEn: 'Winnipeg Office', officeNameFn: 'Bureau de Winnipeg', caseType: 'T2 Corporate', category: 'Tax Return', createdDate: new Date(2024, 6, 18), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-007' },
  { caseNumber: 'T2-008', clientName: 'Maria Rodriguez', accountNumber: 'ACC-12352', caseStatus: 'Active', assignedUserId: 'USER-008', assignedUerName: 'Henry Kim', officeNameEn: 'Edmonton Office', officeNameFn: 'Bureau d\'Edmonton', caseType: 'T2 Partnership', category: 'Amendment', createdDate: new Date(2024, 7, 25), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-008' },
  { caseNumber: 'T2-009', clientName: 'Robert Taylor', accountNumber: 'ACC-12353', caseStatus: 'Closed', assignedUserId: 'USER-009', assignedUerName: 'Ivy Wong', officeNameEn: 'Quebec Office', officeNameFn: 'Bureau de Québec', caseType: 'T2 Trust', category: 'Objection', createdDate: new Date(2024, 8, 14), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-009' },
  { caseNumber: 'T2-010', clientName: 'Jennifer White', accountNumber: 'ACC-12354', caseStatus: 'Review', assignedUserId: 'USER-010', assignedUerName: 'Jack Brown', officeNameEn: 'Victoria Office', officeNameFn: 'Bureau de Victoria', caseType: 'T2 Corporate', category: 'Tax Return', createdDate: new Date(2024, 9, 30), taxYearEnd: new Date(2023, 11, 31), carpProjectNumber: 'CARP-2024-010' }
];

export const dummyFilingPeriods: FilingPeriod[] = [
  { startDate: new Date('2023-01-01'), endDate: new Date('2023-03-31') },
  { startDate: new Date('2023-04-01'), endDate: new Date('2023-06-30') },
  { startDate: new Date('2023-07-01'), endDate: new Date('2023-09-30') },
  { startDate: new Date('2023-10-01'), endDate: new Date('2023-12-31') }
];

export const dummySACaseDetailDTOs: SACaseDetailDTO[] = [
  { caseNumber: 'SA-001', clientName: 'David Chen', accountNumber: 'ACC-22345', caseStatus: 'Active', assignedUserId: 'USER-011', assignedUerName: 'Kelly Zhang', officeNameEn: 'Toronto Office', officeNameFn: 'Bureau de Toronto', workLoad: 'High', category: 'Audit', createdDate: new Date(2024, 1, 10), receivedDate: new Date(2024, 0, 5), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-002', clientName: 'Emma Wilson', accountNumber: 'ACC-22346', caseStatus: 'Pending', assignedUserId: 'USER-012', assignedUerName: 'Mark Johnson', officeNameEn: 'Vancouver Office', officeNameFn: 'Bureau de Vancouver', workLoad: 'Medium', category: 'Review', createdDate: new Date(2024, 2, 15), receivedDate: new Date(2024, 1, 10), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-003', clientName: 'Ryan Murphy', accountNumber: 'ACC-22347', caseStatus: 'Closed', assignedUserId: 'USER-013', assignedUerName: 'Lisa Brown', officeNameEn: 'Montreal Office', officeNameFn: 'Bureau de Montréal', workLoad: 'Low', category: 'Investigation', createdDate: new Date(2024, 3, 20), receivedDate: new Date(2024, 2, 15), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-004', clientName: 'Sophie Martin', accountNumber: 'ACC-22348', caseStatus: 'Active', assignedUserId: 'USER-014', assignedUerName: 'Alex Davis', officeNameEn: 'Calgary Office', officeNameFn: 'Bureau de Calgary', workLoad: 'High', category: 'Audit', createdDate: new Date(2024, 4, 8), receivedDate: new Date(2024, 3, 20), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-005', clientName: 'Nathan Lee', accountNumber: 'ACC-22349', caseStatus: 'Review', assignedUserId: 'USER-015', assignedUerName: 'Rachel Green', officeNameEn: 'Ottawa Office', officeNameFn: 'Bureau d\'Ottawa', workLoad: 'Medium', category: 'Review', createdDate: new Date(2024, 5, 12), receivedDate: new Date(2024, 4, 25), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-006', clientName: 'Olivia Taylor', accountNumber: 'ACC-22350', caseStatus: 'Active', assignedUserId: 'USER-016', assignedUerName: 'Chris Wilson', officeNameEn: 'Halifax Office', officeNameFn: 'Bureau d\'Halifax', workLoad: 'Low', category: 'Investigation', createdDate: new Date(2024, 6, 18), receivedDate: new Date(2024, 5, 30), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-007', clientName: 'Lucas Garcia', accountNumber: 'ACC-22351', caseStatus: 'Pending', assignedUserId: 'USER-017', assignedUerName: 'Amy Chen', officeNameEn: 'Winnipeg Office', officeNameFn: 'Bureau de Winnipeg', workLoad: 'High', category: 'Audit', createdDate: new Date(2024, 7, 22), receivedDate: new Date(2024, 6, 15), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-008', clientName: 'Zoe Anderson', accountNumber: 'ACC-22352', caseStatus: 'Active', assignedUserId: 'USER-018', assignedUerName: 'Sam Miller', officeNameEn: 'Edmonton Office', officeNameFn: 'Bureau d\'Edmonton', workLoad: 'Medium', category: 'Review', createdDate: new Date(2024, 8, 5), receivedDate: new Date(2024, 7, 20), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-009', clientName: 'Ethan Rodriguez', accountNumber: 'ACC-22353', caseStatus: 'Closed', assignedUserId: 'USER-019', assignedUerName: 'Nina Kim', officeNameEn: 'Quebec Office', officeNameFn: 'Bureau de Québec', workLoad: 'Low', category: 'Investigation', createdDate: new Date(2024, 9, 10), receivedDate: new Date(2024, 8, 25), fillingPeriods: dummyFilingPeriods },
  { caseNumber: 'SA-010', clientName: 'Chloe White', accountNumber: 'ACC-22354', caseStatus: 'Review', assignedUserId: 'USER-020', assignedUerName: 'Tony Lee', officeNameEn: 'Victoria Office', officeNameFn: 'Bureau de Victoria', workLoad: 'High', category: 'Audit', createdDate: new Date(2024, 10, 15), receivedDate: new Date(2024, 9, 30), fillingPeriods: dummyFilingPeriods }
];